-- ══════════════════════════════════════════════════════════════════
--  MIGRATION — Execute no Supabase SQL Editor
--
--  TABELAS JÁ EXISTENTES (não alteradas):
--    ✅ chave_pix
--    ✅ tokens_acesso
--    ✅ jogos          ← apenas ALTER TABLE abaixo
--    ✅ grupo_bolao
--    ✅ apuracao_mensal
--
--  O QUE ESTE SCRIPT FAZ:
--    1. Cria a tabela  boloes  (nova)
--    2. Adiciona 3 colunas na tabela  jogos  existente
--    3. Cria função auxiliar  proxima_sequencia
-- ══════════════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";

-- ══════════════════════════════════════════════════════════════════
--  1. TABELA: boloes (nova)
-- ══════════════════════════════════════════════════════════════════
create table if not exists public.boloes (
  id                   bigint generated by default as identity primary key,
  modalidade           text not null check (modalidade in ('Lotofácil','Mega-Sena','Quina','Dupla Sena')),
  concurso             text not null,
  data_sorteio         date not null,
  valor_premio_inicial numeric(12,2) not null default 0,
  valor_cota           numeric(10,2) not null,
  descricao            text,
  status               text not null default 'aberto' check (status in ('aberto','encerrado','sorteado')),
  created_by           uuid references auth.users(id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
) tablespace pg_default;

create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists boloes_updated_at on public.boloes;
create trigger boloes_updated_at
  before update on public.boloes
  for each row execute function update_updated_at();

alter table public.boloes enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename='boloes' and policyname='Leitura pública bolões') then
    create policy "Leitura pública bolões"      on public.boloes for select using (true);
    create policy "Inserção autenticada bolões" on public.boloes for insert with check (true);
    create policy "Atualização autenticada bo"  on public.boloes for update using (true);
    create policy "Deleção autenticada bo"      on public.boloes for delete using (true);
  end if;
end $$;

-- ══════════════════════════════════════════════════════════════════
--  2. ALTER TABLE jogos — adiciona 3 colunas novas
--     (a tabela e todas as colunas existentes são preservadas)
-- ══════════════════════════════════════════════════════════════════

-- Vincula o jogo a um bolão (nullable — não quebra registros antigos)
alter table public.jogos
  add column if not exists bolao_id bigint references public.boloes(id) on delete set null;

-- Código único para o comprovante digital
alter table public.jogos
  add column if not exists codigo_autenticacao uuid default gen_random_uuid();

-- Status de pagamento da cota
alter table public.jogos
  add column if not exists status_pagamento text not null default 'pendente'
    check (status_pagamento in ('pendente','pago'));

-- Preenche codigo_autenticacao nos registros antigos que ficaram null
update public.jogos
  set codigo_autenticacao = gen_random_uuid()
  where codigo_autenticacao is null;

-- Torna not null após preencher
alter table public.jogos
  alter column codigo_autenticacao set not null,
  alter column codigo_autenticacao set default gen_random_uuid();

-- Índices
create index if not exists idx_jogos_bolao_id     on public.jogos(bolao_id);
create index if not exists idx_jogos_participante on public.jogos(lower(participante));
-- Múltiplos jogos do mesmo bolão compartilham o mesmo codigo_autenticacao; não pode ser unique
drop index if exists idx_jogos_auth;
create index if not exists idx_jogos_auth on public.jogos(codigo_autenticacao);

-- RLS (garante que existe)
alter table public.jogos enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename='jogos' and policyname='Leitura pública jogos') then
    create policy "Leitura pública jogos"      on public.jogos for select using (true);
    create policy "Inserção autenticada jogos" on public.jogos for insert with check (true);
    create policy "Atualização autenticada j"  on public.jogos for update using (true);
  end if;
end $$;

-- ══════════════════════════════════════════════════════════════════
--  3. FUNÇÃO: próxima sequência por participante/bolão
--     Usada internamente pelo frontend (também disponível via RPC)
-- ══════════════════════════════════════════════════════════════════
create or replace function proxima_sequencia(p_bolao_id bigint, p_participante text)
returns text language plpgsql as $$
declare
  max_seq integer;
begin
  select max(sequencia::integer)
  into max_seq
  from public.jogos
  where bolao_id = p_bolao_id
    and lower(participante) = lower(p_participante);

  return lpad(coalesce(max_seq, 0) + 1, 3, '0');
end;
$$;

-- ══════════════════════════════════════════════════════════════════
--  FUTURO: rotina de apuração
--  Transfere resultados de jogos premiados para apuracao_mensal
--  (a implementar quando integrar conferência automática ao novo sistema)
--
--  Lógica prevista:
--    1. Busca resultado da Caixa para a modalidade/concurso do bolão
--    2. Compara cada aposta (jogos.aposta) com as dezenas sorteadas
--    3. Se ganhou, insere em apuracao_mensal:
--         modalidade, nome_grupo (boloes.descricao), data, aposta_seq, valor_premio
--    4. Atualiza boloes.status = 'sorteado'
-- ══════════════════════════════════════════════════════════════════
